### ISSUE TITLE
e01500

### ISSUE THREAD

**Issue by feenberg** [donboyd5/synpuf#26]
Why is e01500 synthesized at all? The description is:
**e01500   Total pensions and annuities received.**
There is another variable  e01700 that is
**e01700  Total pensions and annuities in AGI**
Does e01500 have a role in the tax calculation? I don't see where the non-taxable part can be calculated from the total.

dan

**Comment by donboyd5** [comment]
Given that Tax-Calculator checks to see if e01500 >=e01700 it probably is using them in some fashion.

re whether e01500 adds any value that we don't already have in e01700, I can think of reasons why it might.

In particular, since e01500 is total pensions paid, it could be easier than e01700 to link to economic variables if one is forecasting files for future years. Then you'd have to do some sort of split to get e01700 from the forecasted e01500. But that's just a guess.

@andersonfrailey any thoughts on whether one or both variables are used in Tax-Calculator?

**Comment by feenberg** [comment]
Thanks - that helps.

dan
